# ===========================================================
# NAVIGATION
# ===========================================================

nav:
  - About: README.md
  - Get started:
    - Create workspace: get-started/create-workspace.md
    - Common features: get-started/common-features.md
    - Working in terminal: get-started/working-in-terminal.md
  - Ansible-Terraform workspace: 
    - About: ansible-terraform-workspace/README.md
    - Ansible tools: ansible-terraform-workspace/ansible-tools.md
    - Terraform tools: ansible-terraform-workspace/terraform-tools.md


# ===========================================================
# CONFIGURATION
# ===========================================================

site_name: Alnoda Workspaces
repo_url: https://github.com/bluxmit/alnoda-workspaces
site_url: https://alnoda.org
edit_uri: ""

# ===========================================================
# APPEARANCE
# ===========================================================

theme:
  name: 'material'
  favicon: 'assets/favicon.ico'
  logo: 'assets/Alnoda-white.svg'
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: black  
      accent: red
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: black
      accent: red

extra:
  # Link to open when your logo is clicked
  homepage: https://alnoda.org
  host_url: http://localhost

plugins:
  - search
  # Enable Macros and jinja2 templates


extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6




          
 



