# ===========================================================
# NAVIGATION
# ===========================================================

nav:
  - About: README.md
  - Get started:
    - Create workspace: get-started/create-workspace.md
    - Common features: get-started/common-features.md
    - Working in terminal: get-started/working-in-terminal.md
    - Schedule script executions: get-started/schedule-script.md
  - Ansible-Terraform workspace: 
    - About: ansible-terraform-workspace/README.md
    - Ansible tools: ansible-terraform-workspace/ansible-tools.md
    - Terraform tools: ansible-terraform-workspace/terraform-tools.md
  - Base workspace: 
    - About: base-workspace/README.md
  - Codeserver workspace: 
    - About: codeserver-workspace/README.md
  - Elasticsearch workspace: 
    - About: elasticsearch-workspace/README.md
    - Tutorial: elasticsearch-workspace/tutorial.md
  - Erlang-Elixir workspace: 
    - About: erlang-elixir-workspace/README.md
    - Tutorial: erlang-elixir-workspace/tutorial.md
  - Go workspace: 
    - About: go-workspace/README.md
    - Tutorial: go-workspace/tutorial.md
  - IDE workspace: 
    - About: ide-workspace/README.md
  - Java workspace: 
    - About: java-workspace/README.md
    - Tutorial: java-workspace/tutorial.md
  - Kafka workspace: 
    - About: kafka-workspace/README.md
    - Tutorial: kafka-workspace/tutorial.md
  - MkDocs magicspace: 
    - About: mkdocs-magicspace/README.md
    - Docs: https://mkdocs-magicspace.alnoda.org/
  - Node.js workspace: 
    - About: nodejs-workspace/README.md
    - Tutorial: nodejs-workspace/tutorial.md
  - Notebook workspace: 
    - About: notebook-workspace/README.md
    - Working with data: notebook-workspace/working-with-data.md
    - Data exploration: notebook-workspace/data-exploration.md
    - Presentations: notebook-workspace/presentations.md
    - Reports: notebook-workspace/reports.md
    - Productionalize notebooks: notebook-workspace/productionalize.md
    - Pipelines: notebook-workspace/pipelines.md
    - Interactive web app: notebook-workspace/interactive.md
    - Documentation: notebook-workspace/documentation.md
  - PHP workspace: 
    - About: php-workspace/README.md
    - Tutorial: php-workspace/tutorial.md
  - Postgres workspace: 
    - About: postgres-workspace/README.md
    - Tutorial: postgres-workspace/tutorial.md
  - Python workspace: 
    - About: python-workspace/README.md
    - Tutorial: python-workspace/tutorial.md
  - R workspace: 
    - About: r-workspace/README.md
    - Tutorial: r-workspace/tutorial.md
  - Redis workspace: 
    - About: redis-workspace/README.md
    - Tutorial: redis-workspace/tutorial.md
  - Ruby workspace: 
    - About: ruby-workspace/README.md
    - Tutorial: ruby-workspace/tutorial.md
  - Rust workspace: 
    - About: rust-workspace/README.md
    - Tutorial: rust-workspace/tutorial.md
  - Scala workspace: 
    - About: scala-workspace/README.md
    - Tutorial: scala-workspace/tutorial.md
  - SQlite workspace: 
    - About: sqlite-workspace/README.md
    - Tutorial: sqlite-workspace/tutorial.md
  - Streamlit workspace: 
    - About: streamlit-workspace/README.md
    - Tutorial: streamlit-workspace/tutorial.md
  - Ubunntu workspace: 
    - About: ubuntu-workspace/README.md
    - Tutorial: ubuntu-workspace/tutorial.md
    - Run remotely: ubuntu-workspace/remote-wid.md
  - Ubunntu-docker workspace: 
    - About: ubuntu-docker-workspace/README.md
    - Tutorial: ubuntu-docker-workspace/tutorial.md
  


# ===========================================================
# CONFIGURATION
# ===========================================================

site_name: Alnoda Workspaces
repo_url: https://github.com/bluxmit/alnoda-workspaces
site_url: https://docs.alnoda.org
edit_uri: ""

# ===========================================================
# APPEARANCE
# ===========================================================

theme:
  name: 'material'
  favicon: 'assets/favicon.ico'
  logo: 'assets/Alnoda-white.svg'
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: black  
      accent: red
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: black
      accent: red

extra:
  # Link to open when your logo is clicked
  homepage: https://docs.alnoda.org
  host_url: https://docs.alnoda.org

plugins:
  - search
  # Enable Macros and jinja2 templates


extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6




          
 



