# ===========================================================
# NAVIGATION
# ===========================================================

nav:
  - About: README.md
  - Get started:
    - Create workspace: get-started/create-workspace.md
    - Common features: get-started/common-features.md
    - Working in terminal: get-started/working-in-terminal.md
    - Schedule script executions: get-started/schedule-script.md

  - Workspaces:
    - Ansible-Terraform workspace: 
      - About: workspaces/ansible-terraform-workspace/README.md
      - Ansible tools: workspaces/ansible-terraform-workspace/ansible-tools.md
      - Terraform tools: workspaces/ansible-terraform-workspace/terraform-tools.md
    - Base workspace: 
      - About: workspaces/base-workspace/README.md
    - Codeserver workspace: 
      - About: workspaces/codeserver-workspace/README.md
    - Elasticsearch workspace: 
      - About: workspaces/elasticsearch-workspace/README.md
      - Tutorial: workspaces/elasticsearch-workspace/tutorial.md
    - Erlang-Elixir workspace: 
      - About: workspaces/erlang-elixir-workspace/README.md
      - Tutorial: workspaces/erlang-elixir-workspace/tutorial.md
    - Go workspace: 
      - About: workspaces/go-workspace/README.md
      - Tutorial: workspaces/go-workspace/tutorial.md
    - IDE workspace: 
      - About: workspaces/ide-workspace/README.md
    - Java workspace: 
      - About: workspaces/java-workspace/README.md
      - Tutorial: workspaces/java-workspace/tutorial.md
    - Kafka workspace: 
      - About: workspaces/kafka-workspace/README.md
      - Tutorial: workspaces/kafka-workspace/tutorial.md
    - Kubespray workspace: 
      - About: workspaces/kubespray-workspace/README.md
      - Tutorial: workspaces/kubespray-workspace/tutorial.md
    - Mkdocs-workspace: 
      - About: workspaces/mkdocs-workspace/README.md
      - Docs: https://mkdocs-magicspace.alnoda.org/
    - Node.js workspace: 
      - About: workspaces/nodejs-workspace/README.md
      - Tutorial: workspaces/nodejs-workspace/tutorial.md
    - Notebook workspace: 
      - About: workspaces/notebook-workspace/README.md
      - Working with data: workspaces/notebook-workspace/working-with-data.md
      - Data exploration: workspaces/notebook-workspace/data-exploration.md
      - Presentations: workspaces/notebook-workspace/presentations.md
      - Reports: workspaces/notebook-workspace/reports.md
      - Productionalize notebooks: workspaces/notebook-workspace/productionalize.md
      - Pipelines: workspaces/notebook-workspace/pipelines.md
      - Interactive web app: workspaces/notebook-workspace/interactive.md
      - Documentation: workspaces/notebook-workspace/documentation.md
    - PHP workspace: 
      - About: workspaces/php-workspace/README.md
      - Tutorial: workspaces/php-workspace/tutorial.md
    - Postgres workspace: 
      - About: workspaces/postgres-workspace/README.md
      - Tutorial: workspaces/postgres-workspace/tutorial.md
    - Python workspace: 
      - About: workspaces/python-workspace/README.md
    - Python-automate workspace: 
      - About: workspaces/python-automate-workspace/README.md
      - Tutorial: workspaces/python-automate-workspace/tutorial.md
    - R workspace: 
      - About: workspaces/r-workspace/README.md
      - Tutorial: workspaces/r-workspace/tutorial.md
    - Redis workspace: 
      - About: workspaces/redis-workspace/README.md
      - Tutorial: workspaces/redis-workspace/tutorial.md
    - Ruby workspace: 
      - About: workspaces/ruby-workspace/README.md
      - Tutorial: workspaces/ruby-workspace/tutorial.md
    - Rust workspace: 
      - About: workspaces/rust-workspace/README.md
      - Tutorial: workspaces/rust-workspace/tutorial.md
    - Scala workspace: 
      - About: workspaces/scala-workspace/README.md
      - Tutorial: workspaces/scala-workspace/tutorial.md
    - SQlite workspace: 
      - About: workspaces/sqlite-workspace/README.md
      - Tutorial: workspaces/sqlite-workspace/tutorial.md
    - Streamlit workspace: 
      - About: workspaces/streamlit-workspace/README.md
      - Tutorial: workspaces/streamlit-workspace/tutorial.md
    - Theia workspace: 
      - About: workspaces/theia-workspace/README.md
      - Tutorial: workspaces/theia-workspace/getting-started.md
    - Ubunntu workspace: 
      - About: workspaces/ubuntu-workspace/README.md
      - Tutorial: workspaces/ubuntu-workspace/tutorial.md
      - Run remotely: workspaces/ubuntu-workspace/remote-wid.md
    - Ubunntu-docker workspace: 
      - About: workspaces/ubuntu-docker-workspace/README.md
      - Tutorial: workspaces/ubuntu-docker-workspace/tutorial.md
  
  - User guide:
    - Examples:
        - Apt packages:
          - Kakoune: user-guide/examples/apt/kakoune.md
          - SnipKit: user-guide/examples/apt/snipkit.md
        - Nix packages:
          - Glow: user-guide/examples/nix/glow.md
          - Micro: user-guide/examples/nix/micro.md
        - Binary packages:
          - q: user-guide/examples/binary/q.md
          - nnnn: user-guide/examples/binary/nnn.md
        - Python applications:
          - Calibre-Web: user-guide/examples/python/calibre-web.md
          - Label Studio: user-guide/examples/python/label-studio.md
        - Node.js applications:
          - Luckysheet Document: user-guide/examples/node/luckysheet.md
          - Voyager: user-guide/examples/node/voyager.md
          - Trilium: user-guide/examples/node/trilium.md
        - Go applications:
          - cointop: user-guide/examples/go/cointop.md
        - Rust applications:
          - amp: user-guide/examples/rust/amp.md
        - Serverless in-browser:
          - JupyterLite: user-guide/examples/static/jupyterlite.md
        # - Ruby applications:
        # - PHP applications:

  


# ===========================================================
# CONFIGURATION
# ===========================================================

site_name: Alnoda workspaces
repo_url: https://github.com/bluxmit/alnoda-workspaces
site_url: https://docs.alnoda.org
edit_uri: ""

# ===========================================================
# APPEARANCE
# ===========================================================

theme:
  name: 'material'
  favicon: 'assets/laptop-circle.svg'
  logo: 'assets/laptop-circle-white.svg'
  custom_dir: overrides
  font:
    text: Roboto
  icon:
    repo: fontawesome/brands/git-alt
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: docs-light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black  
      accent: red
    - scheme: docs-dark
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: red

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  # - mdx_include:
  #     base_path: docs

extra:
  # Link to open when your logo is clicked
  homepage: https://docs.alnoda.org
  host_url: https://docs.alnoda.org

plugins:
  - search
  # Enable Macros and jinja2 templates

extra_css:
  - stylesheets/modify.css
  - stylesheets/extra.css
  - stylesheets/termynal.css
  - stylesheets/custom.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascript/termynal.js
  - javascript/custom.js
  




          
 



