# ===========================================================
# NAVIGATION
# ===========================================================

nav:
  - About:
    - Intro: about/intro.md
    - What is workspace: about/what-is-workspace.md
    - Workspace separation: about/separation.md 
    - Containerized environments: about/containers.md
    - Alnoda advantages: about/advantages.md
    - Increase productivity: about/productivity.md
    - Improve collaboration: about/collaboration.md
    - Alnoda limitations: about/limitations.md
    - Use-cases: about/use-cases.md
    - Roadmap: about/roadmap.md
    - Contribution: about/contribution.md
    
  - Get started:
    - Launch workspace: get-started/launch-workspace.md
    - Terminal: get-started/terminal.md
    - File browser: get-started/file-browser.md
    - Install Code Editor: get-started/install-code-editor.md
    - Install File Manager: get-started/install-file-manager.md
    - Install Desktop: get-started/install-desktop.md
    - Personalize workspace: get-started/personalize.md
    - Share workspace: get-started/share.md

  - User guide:
    - Workspace:
      - Docker: user-guide/workspace/docker.md
      - User interface: user-guide/workspace/ui.md
      - Base image: user-guide/workspace/base-image.md
      - Pre-installed apps: user-guide/workspace/pre-installed-apps.md
    - Workspace Admin: 
      - Info: user-guide/admin/info.md
      - Metadata: user-guide/admin/meta.md
      - UI customization: user-guide/admin/ui-customization.md
      - Apps and services: user-guide/admin/apps-services.md
      - Terminal: user-guide/admin/terminal.md
      - Notes: user-guide/admin/notes.md
      - Share: user-guide/admin/share.md 
    - Wrk tool:
      - Info: user-guide/wrk/info.md 
    - Cloud deployment:
      - Kubernetes: user-guide/cloud-deployment/kubernetes.md
      - Cloud server: user-guide/cloud-deployment/server.md
    - Install applications:
        - Info: user-guide/install-apps/info.md
        - Alnoda Hub: user-guide/install-apps/alnoda-hub.md
        - APT:
          - Info: user-guide/install-apps/apt/install.md
          - Examples:
            - Kakoune: user-guide/install-apps/apt/kakoune.md
            - SnipKit: user-guide/install-apps/apt/snipkit.md
        - Binary packages:
          - Info: user-guide/install-apps/binary/install.md
          - Examples:
            - Dagu: user-guide/install-apps/binary/dagu.md
            - q: user-guide/install-apps/binary/q.md
            - nnn: user-guide/install-apps/binary/nnn.md
        - Nix:
          - Info: user-guide/install-apps/nix/install.md
          - Examples:
            - Glow: user-guide/install-apps/nix/glow.md
            - Micro: user-guide/install-apps/nix/micro.md
        - Asdf:
          - Info: user-guide/install-apps/asdf/install.md
          - Examples: 
            - Devspace: user-guide/install-apps/asdf/devspace.md
        - Python applications:
          - Info: user-guide/install-apps/python/install.md
          - Examples:
            - Label Studio: user-guide/install-apps/python/label-studio.md
            # - Cooka: user-guide/install-apps/python/cooka.md
        - Node.js applications:
          - Info: user-guide/install-apps/nodejs/install.md
          - Examples:
            - Snippet Box: user-guide/install-apps/nodejs/snippetbox.md
            - Voyager: user-guide/install-apps/nodejs/voyager.md
            - Trilium: user-guide/install-apps/nodejs/trilium.md
            - Neumorphism: user-guide/install-apps/nodejs/neumorphism.md
            - ZeroDivs: user-guide/install-apps/nodejs/zerodivs.md
            - Limus: user-guide/install-apps/nodejs/limus.md
            - Csv-editor: user-guide/install-apps/nodejs/csv-editor.md
            - Convert2svg: user-guide/install-apps/nodejs/convert2svg.md
        - Go applications:
          - Info: user-guide/install-apps/go/install.md
          - Examples:
            - cointop: user-guide/install-apps/go/cointop.md  
        - Rust applications:
          - Info: user-guide/install-apps/rust/install.md
          - Examples:
            - amp: user-guide/install-apps/rust/amp.md
        - Ruby applications:
          - Info: user-guide/install-apps/ruby/install.md
          # - Examples:
        # - PHP applications:
        #   - Info: user-guide/install-apps/php/install.md
          # - Examples:
        - In-browser applications:
          - Info: user-guide/install-apps/in-browser/install.md
          - Examples:
            - JupyterLite: user-guide/install-apps/in-browser/jupyterlite.md
            # - Laverna: user-guide/install-apps/in-browser/laverna.md
    - Build workspaces:
      - Images: user-guide/build-workspaces/images.md
      - Commit workspaces: user-guide/build-workspaces/commit.md
      - With Dockerfile: user-guide/build-workspaces/dockerfile.md


# ===========================================================
# CONFIGURATION
# ===========================================================

site_name: Alnoda workspaces
repo_url: https://github.com/bluxmit/alnoda-workspaces
site_url: https://docs.alnoda.org
edit_uri: ""

# ===========================================================
# APPEARANCE
# ===========================================================

theme:
  name: 'material'
  favicon: 'assets/laptop-red.svg'
  logo: 'assets/laptop-circle-white.svg'
  custom_dir: overrides
  font:
    # text: Lato
    text: Roboto
    # text: Fira Code
  icon:
    repo: fontawesome/brands/git-alt
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: docs-light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black  
      accent: red
    - scheme: docs-dark
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: red

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  # - mdx_include:
  #     base_path: docs

extra:
  # Link to open when your logo is clicked
  homepage: https://docs.alnoda.org
  host_url: https://docs.alnoda.org

plugins:
  - search
  # Enable Macros and jinja2 templates

extra_css:
  - stylesheets/modify.css
  - stylesheets/extra.css
  - stylesheets/termynal.css
  - stylesheets/custom.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascript/termynal.js
  - javascript/custom.js
  




          
 



